name: MS Teams Deploy Card

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - uses: ./
      #   if: always()
      #   with:
      #     github-token: ${{ github.token }}
      #     webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      #     timezone: Australia/Sydney

      - name: Microsoft Teams Deploy Card
        uses: ./
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          card-layout-exit: complete
          show-on-start: false
          custom-facts: |
            - name: Environment
              value: test
